db:
  host: localhost
  adapter: postgres
  database: peterhenrikson
  user: tkellen

email:
  to: peter@peterhenrikson.com
  from: donotreply@peterhenrikson.com
  developer: tyler@sleekcode.net

paypal:
  url_ipn: http://www.paypal.com/cgi-bin/webscr
  recipient: peter@peterhenrikson.com

assets:
  s3: //s3.amazonaws.com/s3.peterhenrikson.com

messages:
  error_submission: Ack!  There are some errors with your submission, please try again.
  error_unknown: An unknown error occurred, please contact tyler@sleekcode.net for help.
  thankyou: "<h3 style='color:#fff;text-align:center'>Thanks for your message&mdash;I'll get back to you as soon as I can!</h3>"
